# -*- coding:utf-8-unix -*-

[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["{{authors}}"]
edition = "2018"

[[bin]]
name = "main"
path = "src/main.rs"

[dev-dependencies]
cli_test_dir = "0.1"
