[tasks.check]
description = "Code check using rust 1.39.0"
command = "cargo"
args = ["+1.39.0", "check"]

[tasks.equip]
description = "Make crates to equiped single text and copy to clipboard."
script = ['''
#!/usr/bin/env bash
cargo equip --remove docs --remove comments --minify libs | xsel -b
echo -e "\nCode copied. Plsease paste and submit your code."
''']

[tasks.submit]
dependencies = ["check", "equip"]
